// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:firebase_core/firebase_core.dart';


// ...

class DefaultFirebaseOptions {
static FirebaseOptions get currentPlatform {
if (kIsWeb) {
return web;
}
switch (defaultTargetPlatform) {
case TargetPlatform.android:
return android;
case TargetPlatform.iOS:
return ios;
case TargetPlatform.macOS:
return macos;
case TargetPlatform.windows:
return windows;
case TargetPlatform.linux:
throw UnsupportedError(
'DefaultFirebaseOptions have not been configured for linux - '
'you can reconfigure this by running the FlutterFire CLI again.',
);
default:
throw UnsupportedError(
'DefaultFirebaseOptions are not supported for this platform.',
);
}
}

static const FirebaseOptions web = FirebaseOptions(
apiKey: 'AIzaSyA6GLVQ68G5cxSX9KppJP-bIj3XELwxQgE',
appId: '1:971570699304:web:f8aec9484622d0f98b291d',
messagingSenderId: '971570699304',
projectId: 'instagramclone-ed418',
authDomain: 'instagramclone-ed418.firebaseapp.com',
storageBucket: 'instagramclone-ed418.appspot.com',
measurementId: 'G-379XPECE82',
);

static const FirebaseOptions android = FirebaseOptions(
apiKey: 'AIzaSyBXkK4QKIAHBVxEb-1JsqeIeSUZP5r6sXg',
appId: '1:971570699304:android:e934b67da0cfee998b291d',
messagingSenderId: '971570699304',
projectId: 'instagramclone-ed418',
storageBucket: 'instagramclone-ed418.appspot.com',
);

static const FirebaseOptions ios = FirebaseOptions(
apiKey: 'AIzaSyBcRHgUWOlpRnJi6Auzw_aAt_pa3uW_ARY',
appId: '1:971570699304:ios:8cd47ef6dc3be82b8b291d',
messagingSenderId: '971570699304',
projectId: 'instagramclone-ed418',
storageBucket: 'instagramclone-ed418.appspot.com',
iosBundleId: 'com.example.sample',
);

static const FirebaseOptions macos = FirebaseOptions(
apiKey: 'AIzaSyBcRHgUWOlpRnJi6Auzw_aAt_pa3uW_ARY',
appId: '1:971570699304:ios:8cd47ef6dc3be82b8b291d',
messagingSenderId: '971570699304',
projectId: 'instagramclone-ed418',
storageBucket: 'instagramclone-ed418.appspot.com',
iosBundleId: 'com.example.sample',
);

static const FirebaseOptions windows = FirebaseOptions(
apiKey: 'AIzaSyA6GLVQ68G5cxSX9KppJP-bIj3XELwxQgE',
appId: '1:971570699304:web:59d6216430eaa6008b291d',
messagingSenderId: '971570699304',
projectId: 'instagramclone-ed418',
authDomain: 'instagramclone-ed418.firebaseapp.com',
storageBucket: 'instagramclone-ed418.appspot.com',
measurementId: 'G-FPZPZP12R8',
);
}
